amount = 1000
# The initial rise ratio to start a pump or dump tracking
riseTrigger = 0.005
# Rise ratio to be in "pumped" 
riseReq = 0.04
# Drop ratio to be in "dumped" 
dropReq = 0.03
# must be less than plateauMargin when plateauCandles > 0
trendFlip = 0.003 
# The absolute amount a candle percentage rise can fluctuate to be considered in no trend
plateauMargin = 0.008
# The minimum number of candles of small fluctuations to be considered on a plateau (Usually triggering a sell or buy after a pump or dump respectively)
plateauCandles = 6
# the Max drop/rise to avoid buying in a correcting market
bearFactor = 1.04
bullFactor = 1.04
# The number of candles that we store to find the trailing market height
trailingHistoryCount = 192
# avoid selling/buying when market has corrected too much
dipFactor = 0.6
bumpFactor = 1.4